Controllers/DirectorController.cs
using HRMS.Models;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HRMS.Controllers
{
    public class DirectorController : Controller
    {
        MayankEntities _db;
        public DirectorController()
        {
            _db = new MayankEntities();
        }
        // GET: Director
        public ActionResult AddEmployee()
        {
           List<SelectListItem> role = _db.Roles.Select(
               x => new SelectListItem
               {
                   Text = x.Name,
                   Value = x.RoleId.ToString()
               }).ToList();

            List<SelectListItem> reportingPersons= _db.Employees.Where(x=> (x.DepartmentId == 2 || x.DepartmentId == 1 )).Select(
    x => new SelectListItem
    {
        Text = x.FirstName +" " +x.LastName,
        Value = x.EmployeeId.ToString()
    }).ToList();
            ViewBag.roles = role;
            ViewBag.reportingPersons = reportingPersons;
            return View();
        }

        [HttpPost]
        public ActionResult AddEmployee(Employee _emp)
        {
            _emp.EmployeeCode = "SIT-433";
            _db.Employees.Add( _emp );
           _db.SaveChanges();
            return RedirectToAction("Index","Home");
        }

        public ActionResult AllEmployees()
        {
            List<Employee> _emp = _db.Employees
                .Include("Employee2")
                .ToList();
            return View(_emp);
        }

    }
}

Views/Director/AddEmployee.cshtml
@using HRMS.Models
@model Employee
@using (Html.BeginForm("AddEmployee", "Director", FormMethod.Post))
{
    @Html.TextBoxFor(x => x.Email);
    <br />
    @Html.TextBoxFor(x => x.Password);
    <br />
    @Html.TextBoxFor(x => x.FirstName);
    <br />
    @Html.TextBoxFor(x => x.LastName);
    <br />
  
    <br />
    @Html.TextBoxFor(m => m.BirthDate, "{0:yyyy-MM-dd}", new { type = "date", })
    <br />
    @Html.RadioButtonFor(m => m.Gender, "M", new { @class = "" })
    @Html.LabelFor(m => m.Gender, "Male")
    @Html.RadioButtonFor(m => m.Gender, "F", new { @class = "ms-3" })
    @Html.LabelFor(m => m.Gender, "Female")
    <br />
    @Html.DropDownListFor(
    m => m.DepartmentId,
    new SelectList(ViewBag.roles, "Value", "Text")
    );

    @Html.DropDownListFor(
m => m.ReportingPerson,
new SelectList(ViewBag.reportingPersons, "Value", "Text")
);

    <button type="submit">Add New User</button>
}

Views/Director/AllEmployees.cshtml
@using HRMS.Models;
@model List<Employee>

<table class="table table-bordered">
    <tr>
        <th>Employee Name</th>
        <th>Birth-date</th>
        <th>Gender</td>
        <th>Role</th>
        <th>Reporting Person</th>
        <th>
            Edit
        </th>
        <th>
            Delete
        </th>
    </tr>
  
    @foreach (Employee i in Model)
    {
        <tr id="@i.EmployeeId">

            <td>@i.FirstName @i.LastName</td>
            <td>@i.BirthDate</td>
            <td>@i.Gender</td>
            <td>@i.Role.Name</td>
            <td>@i.Employee2.FirstName @i.Employee2.LastName</td>
            <td>
                @Html.ActionLink("Edit", "EditEmployee", "Director",
                   new { id = @i.EmployeeId }, new { @class = "btn btn-primary" })
            </td>
            <td>
                @Html.ActionLink("Delete", "DeleteEmployee", "Director",
    new { id = @i.EmployeeId }, new { @class = "btn btn-primary" })
            </td>
        </tr>

    }
</table>